apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vnm8bmn5r-nodejs 
  janus-idp.io/tekton: vnm8bmn5r-nodejs
  backstage.io/kubernetes-id: vnm8bmn5r-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vnm8bmn5r-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml